{
  "version": 1,
  "name": "loreni-tea",
  "type": "static",
  "staticPublishing": {
    "directory": "."
  },
  "routes": [
    {
      "src": "/",
      "dest": "/tea.html"
    },
    {
      "src": "/(.*)",
      "dest": "/tea.html"
    }
  ]
}
